image: node:lts

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - package-lock.json
    - "*/package-lock.json"
    - "*/*/package-lock.json"
    - "*/*/*/package-lock.json"
    - "*/*/*/*/package-lock.json"
    - "*/node_modules/*"
    - "*/*/node_modules/*"
    - "*/*/*/node_modules/*"
    - "*/*/*/*/node_modules/*"

build:
  stage: build
  only:
    - master
  script:
    - git config --global user.email $GITHUB_EMAIL
    - git config --global user.name "nodeful:$GITHUB_TOKEN"
    - git remote set-url origin https://github.com/nodeful/portfolio.git
    - git push origin master
    - npm run ci
