image: node:10.15.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - package-lock.json
    - "*/package-lock.json"
    - "*/*/package-lock.json"
    - "*/*/*/package-lock.json"
    - "*/*/*/*/package-lock.json"
    - "*/node_modules/*"
    - "*/*/node_modules/*"
    - "*/*/*/node_modules/*"
    - "*/*/*/*/node_modules/*"

build:
  stage: build
  only:
    - master
  script:
    - git remote set-url origin https://nodeful:$GITHUB_TOKEN@github.com/nodeful/portfolio.git
    - npm run ci
    - git push origin master
